### ISSUE TITLE
Update Hero Image

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2021.code4lib.org#1]
Needs to be CC-licensed or permissioned appropriately for us to use. Flickr or Pixabay might be productive starting points. Historically, the dimensions of these images have been quite large (3840 × 1670) and heavily landscape-oriented. 

As Julia recommended, feel free to provide a list of keywords to assist with content searches or make specific image proposals in the comments of this issue.

**Comment by dzoladz** [comment]
Here are a few quick proposals of varying style that we can either select or use to spark a conversation:

**Proposal 1:**
Steampunk-esque Fantasy
<img width="1165" alt="Screen Shot 2020-11-01 at 8 38 35 PM" src="https://user-images.githubusercontent.com/10561752/97822132-c87ea000-1c82-11eb-8fa6-702b98b7c833.png">
**Proposal 2:**
Cartoon-esque Cityscape
<img width="1155" alt="Screen Shot 2020-11-01 at 8 36 37 PM" src="https://user-images.githubusercontent.com/10561752/97822199-04196a00-1c83-11eb-8a83-4d3d4ec4d931.png">
**Proposal 3:**
Intentionally Flawless, Artificial Structures
<img width="1155" alt="Screen Shot 2020-11-01 at 8 35 46 PM" src="https://user-images.githubusercontent.com/10561752/97822242-31661800-1c83-11eb-8056-373d43a091a0.png">
**Proposal 4:**
Reality Trumps Fiction Approach: Kuala Lumpar, or any other skyline
<img width="1155" alt="Screen Shot 2020-11-01 at 8 37 38 PM" src="https://user-images.githubusercontent.com/10561752/97822339-8570fc80-1c83-11eb-948d-2a091078db9b.png">

Each of the above proposals explores the city/location approach from without a physical location to reference, which may provide a since of familiarity and continuity to the conference site for previous attendees.

**Comment by andyhickner** [comment]
Of these, i like the playfulness of the first 2; #4 would be my second
choice.

**Comment by thatandromeda** [comment]
https://unsplash.com/ is also an extremely good image source :)

**Comment by jscaffrey** [comment]
I really like all of these written briefs. Of the proposals above, I like the colors/aesthetics of 4 best. I agree the playfulness of 1 and 2 are good. 2 feels a little Gotham to me.

Here are some based on your above briefs:

**Proposal 5**
Glowing City (this is Minato, Japan)
...Building off of "Reality Trumps Fiction Approach: Kuala Lumpar, or any other skyline" I like the colors scheme this gives us access to.

[Minato, Japan](https://unsplash.com/photos/Ys-DBJeX0nE)
![Screenshot_2020-11-03 code4lib 2021](https://user-images.githubusercontent.com/10285039/98040763-d5200700-1dee-11eb-8776-459ab95d6542.jpg)

**Proposal 6**
Atlantis ...Building off of fantasy and playful approaches in 1 and 2 ...

![Screenshot_2020-11-03 code4lib 2021(2)](https://user-images.githubusercontent.com/10285039/98042451-9ccdf800-1df1-11eb-9cb8-edd9a6d06bcd.jpg)

**Proposal 7**
[Alternate Steampunk/fantasy](https://flic.kr/p/25jeNQC)

Flickr is sealed like a vault, so click the link to see the image

**Comment by dzoladz** [comment]
This more a think I about it, using a real city's skyline creates an implied and unintended association between the conference and that geographic place.

Unless there are strong objections to doing so, let's focus our efforts towards the whimsical, fantasy, and more playful elements in our proposals.

- Let's submit any additional proposals to this issue by the end of this week
- Next week, we'll choose a direction.
  - There are several ways we could go about selecting a direction for the hero image. I'd recommend that we use a ranking question in a tool like SurveyMonkey to see if there's a clear path forward regarding our proposals. I'm open to other ideas and suggestions for an approach.

**Comment by dzoladz** [comment]
Adding an example of **Proposal 7** to use for ranking survey

<img width="1156" alt="Screen Shot 2020-11-08 at 7 36 12 PM" src="https://user-images.githubusercontent.com/10561752/98488990-23237900-21fa-11eb-9010-bf8858ca3495.png">

**Comment by dzoladz** [comment]
Adding geometric example for our meeting next week
![geometric](https://user-images.githubusercontent.com/10561752/99001757-6a1ab280-2509-11eb-87ea-8abfd90e13de.png)

![scheme-A](https://user-images.githubusercontent.com/10561752/99002318-3724ee80-250a-11eb-9ab8-3be20b0bcb38.png)

![scheme-B](https://user-images.githubusercontent.com/10561752/99002326-3a1fdf00-250a-11eb-8832-77a5e1d6a724.png)

**Comment by dzoladz** [comment]
Geometric design and colors selected. Example themes forthcoming in #2

**PR Forthcoming**
