### ISSUE TITLE
Theme for peri conference state

### ISSUE THREAD

**Issue by jscaffrey** [code4lib/2021.code4lib.org#101]
- [ ] - Apply theme colors to `peri` conference state
- [ ] - Check for color contrast / accessibility
- [ ] - Ideally, add visual elements to the `color-test.md` page for future years.

Generally, should look better than this (I'm not sure how it could look worse) and be accessible:

<img width="1158" alt="Conference schedule with horrid colors" src="https://user-images.githubusercontent.com/10285039/102426285-0c342b80-3fdd-11eb-8ba5-df4cc8a6567b.png">

![Screenshot_2020-12-16 Schedule](https://user-images.githubusercontent.com/10285039/102426378-3e458d80-3fdd-11eb-8658-131216d50dc8.png)

I'll also go ahead and assign myself, and I'm happy to work with others, too. If you self assign also, reach out to me at jcaffreyhill@towson.edu so that we can work together.

**Comment by jscaffrey** [comment]
<img width="1187" alt="" src="https://user-images.githubusercontent.com/10285039/105934521-5c5fce00-601e-11eb-9984-6052a070f55c.png">
Mock-up of dark mode of peri homepage / event area.

**Comment by dzoladz** [comment]
Included in PR #153. Closing Issue.
