### ISSUE TITLE
Thermometer Display for the Angel Fund

### ISSUE THREAD

**Issue by mjingle** [code4lib/2021.code4lib.org#102]
Hi! Would it be possible to make the Angel Fund's progress thermometer display appear? We will be accepting individual donations soon and would like to show the fundraising progress so far to the community.

Rather than using multiple thermometer displays to show the progress of the Angel Fund and its Matching Funds, there would be one thermometer to show the overall amount raised by the Angel Fund's individual donations.

The thermometer feature is located in this file and would need to be turned on: https://github.com/code4lib/2021.code4lib.org/blob/main/general-info/angel-fund.html

I know we have to supply a link to a google spreadsheet (for the money tally) to you. Please let me know what else you need from the Sponsorship committee!

**Comment by dzoladz** [comment]
I can assign myself to add a thermometer to the site.

The Spreadsheet needs to follow a very particular format for thermometer.js to be able to parse it properly. The easiest way to create one for this year is copy an old version and update it.

For example:
https://docs.google.com/spreadsheets/d/1DTMECsa9KznCK90UQRjyZ6X_SqI0Zeq7-DZ_ByDsM6w/edit#gid=0

It follows this format:

- There are three worksheets (in this order): Donations, Goals, and Total
- Donations must have a header row and three columns: reference number (not used but still must be included or offsets will be wrong), amount (integer or floating point), and fund tag (must match a "fund" under the Goals spreadsheet)
- Goals must have a header row and three columns: fund label (shown on the website), fund code (the matching identifier used under Donations), and goal (integer or floating point)
- Total has only a single cell in the upper left (A1) position that shows the total donated so far (it can be an =SUM() equation)

Once you have a Spreadsheet created for this year, make it public and share the URL with me on **Slack** or via email derekz@ohionet.org. I'll need to reference the Spreadsheet key in the script to pull in the data.
