### ISSUE TITLE
Gearing up for Sponsors

### ISSUE THREAD

**Issue by mjingle** [code4lib/2021.code4lib.org#124]
We have our first sponsors coming in! This issue is a heads up that the Sponsorship page will need to become visible by Friday, Jan 22nd. (Please leave the Prospectus page public though.) 

I know there's a metadata format to follow with regard to sponsor logos, names, links, etc., which I'm happy to submit as a PR. I wasn't sure if there's other website infrastructure that needs to be modified accordingly. Thank you in advance!

**Comment by dzoladz** [comment]
I believe the sponsor data file needs to be initially created before any of the associated site logic can respond accordingly. If you can provide some info and a logo for a first sponsor, I can begin to set up the conference site for displaying sponsors.

For reference, here's the key:value format of the YAML file. 

```
- name: Tony's DJ Sets, Inc.
  img: /assets/img/sponsors/two.svg
  link: https://www.youtube.com/watch?v=0eLGgp_r_Yg
  level: diamond
  annotation: "Closed Captioning"

- name: DΛTΛSSSSSETTE
  img: /assets/img/sponsors/three.svg
  link: https://musicforprogramming.net/
  level: gold
  transcription: true
```

Once the initial sponsor data file is in place, and any adjustments to the site architecture have been made to support sponsor display, you can make a PR with additional sponsorships as they come in.

**Comment by mjingle** [comment]
@dzoladz Thank you for this information. Will get an initial PR in. I'm not planning to use the conference plug-in at all.

**Comment by dzoladz** [comment]
Thank you! PR is ready to merge when you have the time.
