### ISSUE TITLE
Revert Whova Widgets

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2021.code4lib.org#128]
VPC decided to not use Whova widgets.

![source](https://user-images.githubusercontent.com/10561752/105634116-936d8e00-5e2a-11eb-8355-af85b3af2216.gif)

I'll assign myself to this issue, as I'll need to work with Kathy to get the data extracted from Whova a few times over the next few weeks.

**Comment by jscaffrey** [comment]
Guessing this means the Schedule page will need to be ready to go. Shall I prioritize getting a theme ready (#101 )?

**Comment by dzoladz** [comment]
@jscaffrey That would be great! 👍
