### ISSUE TITLE
Repository for slides presentation

### ISSUE THREAD

**Issue by ranti** [code4lib/2021.code4lib.org#141]
Currently, Accessibility Comittee provided link for presentation slides upload to https://osf.io/meetings/c4l21/, which currently does not exist. Need confirmation from the PPC to create the space.

**Comment by dzoladz** [comment]
I've requested a meeting space for c4l21.

For future reference, here's a link to the form: https://docs.google.com/forms/d/e/1FAIpQLSeBq4CfC5CjTBz49TP2dO9ZIsQc6QAAJFUoUbkS767Le9twLw/viewform?gxids=7628
