### ISSUE TITLE
Update Conference Schedule

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2021.code4lib.org#147]
Kathy provided an extract from Whova with finalized schedule. I'll update the information on the website over the next few days.

**Comment by dzoladz** [comment]
Since we're investigating the option to switch time display to the local timezone, I'd like to propose that we either use the `icosahedron.svg` image or a colored dot to replace the clockface images in this year's schedule.

Do you think that using the `icosahedron.svg` will saturate the theme image throughout the site and take away from its uniqueness to the conference theme?

<img width="1067" alt="Screen Shot 2021-02-12 at 7 11 24 AM" src="https://user-images.githubusercontent.com/10561752/107766669-cad0ab80-6d01-11eb-8943-7a6431548ec6.png">

**Comment by jscaffrey** [comment]
Looks great to me! I think echoing it in this location will be a strong addition. Thanks @dzoladz !
