### ISSUE TITLE
Low contrast issue?

### ISSUE THREAD

**Issue by cdmo** [code4lib/2021.code4lib.org#156]
Just a heads up that it looks like the pink on off-white body text links do not pass WCAG AA at 3.37:1 (using WAVE Firefox plugin). I'd PR a change but not sure what to suggest 😅 

![Screen Shot 2021-02-15 at 3 25 42 PM](https://user-images.githubusercontent.com/523381/107990354-4badd280-6fa2-11eb-8a7b-7be36e92ae6c.png)

**Comment by dzoladz** [comment]
Thanks for opening this issue, @cdmo. This contract issue is resolved in PR #153. That PR is still waiting on another member of the Website Working Group to review it. It's a large PR, as it incorporates all of the conference presentations/schedule.

<img width="1310" alt="Screen Shot 2021-02-15 at 4 48 49 PM" src="https://user-images.githubusercontent.com/10561752/107996307-14ddb980-6fae-11eb-9a28-c433d2f1ee06.png">

**Comment by cdmo** [comment]
Sounds good, thanks.
