### ISSUE TITLE
Update livestream/Whova link while conference is live

### ISSUE THREAD

**Issue by jscaffrey** [code4lib/2021.code4lib.org#159]
While conference is happening, there should be some way to get there from the webpage, even if email is encouraged to be the primary way people get there.

Former "Livestream" button should be replaced with a link to Whova (TBD).

Text for the button also TBD, but potentially "Registered? Join Live"

**Comment by dzoladz** [comment]
I explained our use case and ideas for implementing a quick access button to the Whova 'live stream' from the conference website. Kathy is going to investigate how the access controls work in Whova this week and get back to us.

**Comment by dzoladz** [comment]
I'll make a PR with updates for adding a Whova button to the site hero, per a conversation with Kathy Azevedo.
