### ISSUE TITLE
Skip to Main Content

### ISSUE THREAD

**Issue by yarnetsky** [code4lib/2021.code4lib.org#174]
The skip-to-content link is acting oddly. When clicked, it jumps to the right part of the page, but then the focus jumps back to the skip to main link. Screen reader then repeats the skip to main link. (tested with VoiceOver). 

### Related
* Individual Day schedule pages lacking `id="main"` for the skip to main link.
* Speakers, Schedule, and other pages which do have `#main` have same bounce back to skip link error as homepage.

**Comment by jscaffrey** [comment]
I researched this issue and found:
https://axesslab.com/skip-links/
Any chance you were using a mobile device, @yarnetsky ?

**Comment by yarnetsky** [comment]
sorry I missed this. I tested on desktop Chrome and Firefox for mac. Happily, the issue of focus jumping back seems to have disappeared. 

The schedule pages are still missing the `id="main"` that the link skips to. (other pages I've tested it works just fine)
