### ISSUE TITLE
Non-visible links being captured during tab navigation

### ISSUE THREAD

**Issue by yarnetsky** [code4lib/2021.code4lib.org#178]
- On speakers page, the link inside the speaker-info box captures the tab whether the speaker is active or not. Needs JS to set attribute for link to `tabindex="-1"` unless the speaker box is .selected, then flip to `tabindex="0"`

**Comment by dzoladz** [comment]
@yarnetsky Created PR #205 to address this issue. It's the same solution that was applied to the workshop speaker boxes. Take a look and feel free to merge.
