### ISSUE TITLE
Update Look & Feel (i.e. Colors/Theme)

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2021.code4lib.org#2]
We'll need to update the colors, fonts, and overall theme of the site. The hero image could guide the theme colors, or an inspiring color scheme could be melded with the appropriate hero image.

For inspiration, tools similar to [coolors.io](http://coolors.io/) might be useful.

Previous conference themes were sports-related. The San José Sharks color scheme was used in 2019. Pittsburgh Pirates yellow & black was used last year.

**Comment by dzoladz** [comment]
Website Working Group selected Proposal B.

@jscaffrey @Meng-MiamioH @dzoladz Let's post our overall site theme proposals to this issue.

**Proposal B**

<table>
  <tr>
    <td width="50%"><img src="https://user-images.githubusercontent.com/10561752/99001757-6a1ab280-2509-11eb-87ea-8abfd90e13de.png"></td>
    <td><img src="https://user-images.githubusercontent.com/10561752/99002318-3724ee80-250a-11eb-9ab8-3be20b0bcb38.png"></td>
  </tr>
</table>

[Coolors Palette](https://coolors.co/f5f5f5-fa62f0-00d5c0-061a40-041f1e)
```
- Oxford Blue (#061A40) or Dark Jungle Green (#041F1E)can be used as a background.
- "Cultured" white (#F5F5F5) can be used as a foreground with Oxford Blue (#061A40) or Dark Jungle Green (#041F1E) background with sufficient contrast to WCAG 2.0 AAA for regular font, larger font, and visual components (icons, etc.).
- Turquoise (#00D5C0) can be used as a foreground with Oxford Blue (#061A40) or Dark Jungle Green (#041F1E) background with sufficient contrast to WCAG 2.0 AAA for regular font, larger font, and visual components (icons, etc.).
- Shocking Crayola Pink (#FA62F0) can be used as a foreground with Dark Jungle Green (#041F1E) background for WCAG AA, but it does not meet WCAG AAA for regular font (large font and visual components like icons okay).
- For any other combination (e.g. "Cultured" white (#F5F5F5) on Turquoise (#00D5C0) , Shocking Crayola Pink (#FA62F0) on Oxford Blue (#061A40), do a test.)
- Feel free to use shades or tints of colors to achieve accessible results.
```

**Comment by jscaffrey** [comment]
Created a PR with hero image replaced.

**Comment by yarnetsky** [comment]
Re: other combinations -- 
+ Cultured white (#F5F5F5) on Turquoise (#00D5C0) fails at all sizes (AA and AAA)
+ Shocking Crayola Pink (#FA62F0) on Oxford Blue (#061A40) could work for larger text (fails AAA on regular text)

**Comment by jscaffrey** [comment]
First time doing a draft pull request. Progress so far included:

- Adding theme colors
- Styling testimonial region
- Styling hero region
- Styling footer region

**Comment by dzoladz** [comment]
@jscaffrey Would like feedback on your draft theme? If so, would you prefer that we add comments to this issue? Or something else?

**Comment by dzoladz** [comment]
@Meng-MiamiOH is also working on a proposal for applying the color scheme, so anticipate another branch in the repo shortly.

I know I mentioned contributing a third version, but I'm not going to have the time to explore the colors myself.
