### ISSUE TITLE
Content Review for 2021

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2021.code4lib.org#3]
We need to read through every page for information that is outdated, not yet known, or perhaps completely irrelevant to a fully virtual conference. The 'General Info' and 'Conduct & Safety' pages and subpages surely contain information that we'll need to update... and otherwise, carefully consider. For instance, what does the photo policy mean in a fully virtual conference?

To start us off, I'll take the following sections and review them:
- [ ] Sponsors page
- [ ] Twitter handles and hashtags

As you move through the site, if you see area for accessibility improvements or places where a hard-coded value should be changed to a variable, let's document those for future updates.

**Comment by andyhickner** [comment]
I've reviewed the following pages and flagged obvious changes:
### Conduct
- [ ] Emergency Resources: remove entire section?
- [ ] Community Support Volunteers: will require updating with this year's volunteers
- [ ] Photography Policy: Remove entire section? Revise to reflect virtual format?
### General Info
- [ ] Attend: delete "Health & Wellness," "Can't attend in person?" 
- [ ] Venues: delete?
- [ ] Accessibility: Mic sections are not applicable as written this year
- [ ] Scholarships will require updating
- [ ] First Timers: Food, Newcomer Dinner, Reception
### Schedule

- [ ] entire page will require ongoing update as schedule is developed

### Speakers
- [ ] will require update once they are selected

**Comment by jscaffrey** [comment]
There is also pierogi: assets/img/theme-images/idol.jpg

Appears on homepage
Could be a separate issue. Feel free to assign to me - brainstorming a polygon-like replacement.

**Comment by dzoladz** [comment]
@jscaffrey Done. Opened issue #25 to replace the pierogi and assigned you to it.

**Comment by dzoladz** [comment]
I've assigned myself to issue #11. Since that's the final section of our initial review, I'm closing this one out. For any additional content areas the need revision, please open a fresh issue for us to handle the specific issue.
