### ISSUE TITLE
Update Prospectus for 2021

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2021.code4lib.org#4]
I'll reach out to Mary J. about the status of our sponsor prospectus for this year.

**Comment by dzoladz** [comment]
We'll need to anticipate several weeks before we'll have a prospectus available.

**Comment by dzoladz** [comment]
@mjingle will be providing a PR to us  by the end of this week.

**Comment by mjingle** [comment]
@dzoladz I'm getting a "remote: Permission to code4lib/2021.code4lib.org.git denied to mjingle" message when I try to push my commit to a PR.

**Comment by mjingle** [comment]
Will be warning y'all now that the prospectus has changed significantly from last year.

**Comment by mjingle** [comment]
Prospectus for 2021 will include 6 general sponsorship levels -- Platinum, Gold, Silver, Bronze, Contributor, and Supporter -- and 2 targeted sponsorship levels -- Captioning and Post-Conference Video Production.

The submitted PR, when it happens, will need a second set of eyes to make sure the formatting meets aesthetic standards. (Your help is appreciated in advance!)

**Comment by dzoladz** [comment]
@mjingle I've sent you an invite. Once accepted, you'll have the permissions that you need to open a PR directly to this repo. Feel free to assign me as a reviewer. Thanks!
