### ISSUE TITLE
Improve the consistency of color application to division borders and hr elements

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2021.code4lib.org#44]
Or, if there's a semantic reason to use multiple colors, we'll need to create definitions and rules for when to apply a specific color.

**Examples:**
![Screen Shot 2020-11-23 at 4 57 28 PM](https://user-images.githubusercontent.com/10561752/100020182-6579b800-2dad-11eb-8be7-a572579410b9.png)
![Screen Shot 2020-11-23 at 4 57 34 PM](https://user-images.githubusercontent.com/10561752/100020189-67437b80-2dad-11eb-9725-a3622607e8ed.png)

**Comment by jscaffrey** [comment]
Currently `section` borders are pink and `h1`, `h2`, `h3`, ... borders are white.
Probably easiest to make them all pink.
