### ISSUE TITLE
modify .svg curly braces to fit 2021 color scheme

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2021.code4lib.org#47]
At the moment, it's still using the Pittsburgh yellow.
![Screen Shot 2020-11-23 at 5 19 03 PM](https://user-images.githubusercontent.com/10561752/100021815-0ff2da80-2db0-11eb-903e-39f57056a292.png)

**Comment by jscaffrey** [comment]
Good news is honey yellow added back into this year's color scheme - See Issue #43
