### ISSUE TITLE
Change Planning Committee name and email

### ISSUE THREAD

**Issue by highermath** [code4lib/2021.code4lib.org#58]
Change Local Planning Committee to Planning Committee. Change code4lib@gmail.com to code4lib@concentra-cms.com.

We can't find any information about accessing code4lib@gmail.com.

**Comment by ranti** [comment]
Email information on /data/conf.yml is correct.  first_timer.html on PR #59 needs to be changed to use variable `main-conf-email` instead of hardcoded in.

**Comment by dzoladz** [comment]
I've pushed another commit to PR #59 to use the variable from `/_data/conf.yml`

**Comment by ranti** [comment]
Close per PR #59
