### ISSUE TITLE
Main Navigation Hover Does Not Use Turquoise

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2021.code4lib.org#60]
At the moment, hovering over a main navigation element changes the color to a lighter grey. Using turquoise on hover events may better integrate with the other components of the site.
 
![Nov-28-2020 18-31-46](https://user-images.githubusercontent.com/10561752/100528316-94c36700-31a9-11eb-8119-1cb9f89650bc.gif)

**Comment by dzoladz** [comment]
What do others think about making this change?

**Comment by ranti** [comment]
I'm fine with changing the mouseover color to bright turquoise. I also suggest to change the default color from grey to white. Grey on black is not easy to read.

**Comment by jscaffrey** [comment]
Agree!
