### ISSUE TITLE
Add/update photography statement

### ISSUE THREAD

**Issue by jscaffrey** [code4lib/2021.code4lib.org#70]
On /conduct, update the Photography statement to the following colleagues editing the Code of Conduct : 

Sharing your web camera
•	Neither attendees nor presenters will be expected to have their web camera on at any time.
•	If you do leave your camera on, please be aware that others may take screenshots that include your image.
Taking screen captures
•	For post-conferences or smaller group events, if you want to take a screenshot or screen recording of attendees, please provide notice before doing so and give adequate time for those who do not wish to be recorded to turn off their cameras.

**Comment by dzoladz** [comment]
@jscaffrey Are we ready to merge #120 ?
