### ISSUE TITLE
Tab Order Gets Caught by Hidden Div

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2021.code4lib.org#79]
On the keynotes/speakers page, the tab order gets caught by pop-up speaker bio section, even when it is hidden.

> I think section needs `aria-hidden=true` when the box is not exposed so the tab order bypasses the link -- Jerry

**Comment by yarnetsky** [comment]
I did some more research on this. I believe this is the solution -- include the attribute `tabindex="-1"` to the links in question. Then use JS switch it to `tabindex="0"` when the speaker pane is active. the -1 is essentially a skip this link in the tab order.

**Comment by dzoladz** [comment]
Since the VPC decided to move away from the Whova widgets, this issue will be back. I'll assign myself to it and implement a fix along with the work of populating the sessions, speakers, and schedule from whatever can be exported from Whova.
